version: "3.9"

services:
  backend:
    build: ./backend
    container_name: westa-ocr-backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

  frontend:
    image: nginx:1.25-alpine
    container_name: westa-ocr-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
